### ISSUE TITLE
Todo list for 2.0 release

### ISSUE THREAD

**Issue by devraj** [anomaly/prestans#26]
Features:
- [x] Restore serialisation code in new Response class
- [x] Restore request and response parsers
- [x] Restore attribute filters
- [x] Restore parameter sets
- [x] Restore authentication provider
- [x] Restore authentication decorators
- [x] Error message serialisation to responses
- [x] Restore Data Adapters

Testing:
- [ ] Test model parsing

Enhancements:
- [ ] Update regex match for router
- [ ] Throttle provider
- [ ] Cache provider

Documentation
- [x] Finalise documentation pattern
